### ISSUE TITLE
Version problem on npm

### ISSUE THREAD

**Issue by kennynaoh** [clineamb/bootstrap-drawer#13]
Hello @clineamb ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
I saw the latest version 1.0.5 on [npm](https://www.npmjs.com/package/bootstrap-drawer), but the version in ```dist/js/drawer.js``` shows v1.0.3.
Please help us confirm that.
Thanks very much!

https://github.com/cdnjs/cdnjs/issues/7350
https://github.com/cdnjs/cdnjs/pull/7950

**Comment by clineamb** [comment]
Hi @kennynaoh 

Thanks for adding my plugin!  I've fixed the version issues in commit 70a649e67b34c96d265b0b54044e7e6f25667a48.  In addition, I added the version to the LESS/CSS to sync them to the current NPM version number (1.0.5).

Let me know if there's anything else I can do to help!

**Comment by kennynaoh** [comment]
Hi @clineamb ,
oops!
I install the v1.0.5 of bootstrap-drawer on [npm](https://www.npmjs.com/package/bootstrap-drawer).
But the version in `dist/js/drawer.js` still shows `Bootstrap: drawer.js v1.0.3`.
Please help confirm that.
Thanks very much!

**Comment by clineamb** [comment]
@kennynaoh 

I pushed up changes again (apparently when I `npm install`'d it, I had a typo and it was 1.0.6.  I pushed up again and everything should be 1.0.5 now.  I ran `npm install bootstrap-drawer` and got the appropriate version.

(:

**Comment by kennynaoh** [comment]
Hello @clineamb ,
I think the version on npm release 1.0.5 in `dist/js/drawer.js` is still v1.0.3
I found that maybe you can't update it.
Maybe you should release the new version to fix it.
Thanks!

**Comment by clineamb** [comment]
@kennynaoh Alright, I published 1.0.6. Let me know if this is ok now.

**Comment by kennynaoh** [comment]
@clineamb 
I think it's ok now.
Thanks for your help!

**Comment by clineamb** [comment]
Great! Thank you!
